myDjangoWebProject/urls.py
"""
Definition of urls for myDjangoWebProject.
"""

from datetime import datetime
from xml.dom.minidom import Document
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings



urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Войти',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('links/', views.links, name='links'),
    path('feedback/', views.feedback, name='feedback'),
    path('registration/', views.registration, name= 'registration'),
    path('blog/', views.blog, name= 'blog'),
    path('blogpost/<int:parametr>/', views.blogpost, name='blogpost'),
    path('newpost', views.newpost, name='newpost'),
    path('videopost', views.videopost, name='videopost')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""
from django.db import models
from.models import Comment
from.models import Blog

from pickle import FALSE
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _



class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Логин'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))
class FeedbackForm(forms.Form):
    """Форма обратной свзязи на сайте"""
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    email = forms.EmailField(label='Ваш e-mail', min_length=7, max_length=100)
    gender = forms.ChoiceField(label='Ваш пол',
                               choices=[('1','Мужской'),('2','Женский')],
                               widget = forms.RadioSelect,initial=1)                              
    message = forms.CharField(label='Ваш отзыв о путешествии', 
                              widget=forms.Textarea(attrs={'rows':8, 'cols':50}))
    recommendation = forms.ChoiceField(label='Порекомендуете ли наш сайт?',
                                        choices=(('1','Точно буду рекомендовать'),
                                                 ('2','Вероятно порекомендую'),
                                                 ('3','Не буду рекомендовать'),
                                                 ('4','Затрудняюсь ответить')), initial=1)
    notice = forms.BooleanField(label='Получать новости о скидках и горящих предложениях ',
                                required=False)

class CommentForm (forms.ModelForm):
    class Meta:
      model = Comment # используемая модель
      fields = ('text',) # требуется заполнить только поле text
      labels = {'text': "Комментарий"} # метка к полю формы text

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'description', 'content', 'image',)
        labels = {'title': "Заголовок", 'description': "Краткое содержание", 'content':"Полное содержание", 'image': "Картинка"}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Мы подберем лучший тур по цене туроператора и подготовим необходимые документы. Кроме того, дадим полезные советы, которые помогут получить максимум удовольствия и впечатлений от поездки! Вся наша работа направлена на то, чтобы каждый человек нашел идеальный вариант отдыха для себя и своих близких.</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}
<br>
<h2>{{ title }}</h2>
<br />
{% for post in posts %}
<hr />
<div class="">
    <h2> {{post.title}} </h2>
    <h4> {{post.posted}} </h4>
    <p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
    <p> {{post.description}} </p>
</div>
{% endfor %}
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<br>
<br>
<h2> {{post_1.title}} </h2>

{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
<img src="{{ post_1.image.url }}" alt=" Картинка статьи блога" />
{% endif %}

<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}

{% if user.is_authenticated %}
<h3>Добавить комментарий</h3>
<form method="POST">
    {% csrf_token %} {# защита от атак CSRF#}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default"> Отправить комментарий </button>
    </div>
</form>
{% else %}
<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}
<hr>
<br>
{% for comment in comments %}
<hr />
<h7> {{comment.date}} </h7>
<h5> {{comment.author}} </h5>
<p> {{comment.text|linebreaksbr}} </p>
{% endfor %}

<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    БарселонаТревел<br />
    Москва, Туристская ул. 5<br />
    <abbr title="Телефон">Телефон:</abbr>
    +7(495)158-11-11
</address>

<address>
    <strong>Техническая поддержка:</strong>   <a href="mailto:Support@example.com">info@barselonatrevel.ru</a><br />
    <strong>Отдел маркетинга:</strong> <a href="mailto:Marketing@example.com">Marketing@barselonatrevel.ru</a>
</address>

{% endblock %}

app/templates/app/feedback.html
    {% extends "app/layout.html" %}
    {% block content %}
    {% if form != None %}
    <br>
    <h2>Пожалуйста, оставьте свой отзыв</h2>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            <label for="{{form.name.id_for_label}}">{{form.name.label}}:</label>
            {{form.name}}<br><br>
            <label for="{{form.email.id_for_label}}">{{form.email.label}}:</label>
            {{form.email}}<br><br>
            <label for="{{form.gender.id_for_label}}">{{form.gender.label}}:</label>
            {{form.gender}}<br><br>
            <label for="{{form.message.id_for_label}}">{{form.message.label}}:</label>
            {{form.message}}<br><br>
            <label for="{{form.recommendation.id_for_label}}">{{form.recommendation.label}}:</label>
            {{form.recommendation}}<br><br>
            <label for="{{form.notice.id_for_label}}">{{form.notice.label}}:</label>
            {{form.notice}}<br><br>
            <input type="submit" value="Отправить" id="one">
            <script>
                function one_click() {
                    $('#one').css('color', '#f43a09');
                }
                $('#one').click(one_click);
                function one_mouseover() {
                    $('#one').css('background-color', '#ffb766');
                }
                $('#one').mouseover(one_mouseover);
                function one_mouseout() {
                    $('#one').css('background-color', 'white');
                }
                $('#one').mouseout(one_mouseout);


                $('#id_name').focus(name_focus);
                function name_focus() {
                    $('#id_name').css('background-color', '#ffb766');
                }
                $('#id_name').blur(name_blur);
                function name_blur() {
                    $('#id_name').css('background-color', 'white');
                }

                $('#id_email').focus(email_focus);
                function email_focus() {
                    $('#id_email').css('background-color', '#ffb766');
                }
                $('#id_email').blur(email_blur);
                function email_blur() {
                    $('#id_email').css('background-color', 'white');
                }


       
            </script>
        </form>
    </div>
    {% else %}
    <br>
    <h3>Благодарим за ваш отзыв!</h3>
    <br>
    <h4>Вы сообщили о себе следующее:</h4>
    <ul>
        <li><span>Имя:</span> {{data.name}}</li>
        <li><span>E-mail:</span> {{data.email}}</li>
        <li><span>Ваш пол:</span> {{data.gender}}</li>
        <li><span>Ваш отзыв:</span> {{data.message}}</li>
        <li><span>Ваши рекомендации:</span> {{data.recommendation}}</li>
        <li><span>Получать новоти и предложения на e-mail:</span> {{data.notice}}</li>
    </ul>
    {% endif %}
    {% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
<div class="jumbotron">
    <h1>БарселонаТревел</h1>
    <p class="lead">БарселонаТревел - это команда единомышленников, людей увлеченных путешествиями.  Каждый ваш отпуск мы организовываем, как свой. Мы знаем как важно выбрать подходящий курорт и качественный отель, чтобы на отдыхе получать только положительные эмоции.</p>
    <p><a href="myDjangoWebProject/about.html" class="btn btn-primary btn-large">Больше о нас &raquo;</a></p>
</div>
{% load static%}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/египет1.JPG'%} " alt="Первый слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Почему Египет летом — это все-таки хорошо
                    <a class="btn btn-default" href="{% url 'blog' %}">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/мальдивы1.JPG'%}" alt="Второй слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    7 правил жизни мальдивианцев, которые нас поразили
                    <a class="btn btn-default" href="{% url 'blog' %}">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/оаэ1.JPG'%} " alt="Третий слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Бахрейн — это ОАЭ 30 лет назад
                    <a class="btn btn-default" href="{% url 'blog' %}">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Подобрать тур</h2>
        <p>
            Подобрать, забронировать и оплатить тур и получить документы  — все можно сделать  дистанционно или в офисе  — как вам удобно.
        </p>
        <p><a class="btn btn-default" href="{% url 'about' %}">Подобрать тур &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Вылеты - вся Россия</h2>
        <p>Неважно в каком городе вы живете — мы работаем с вылетами из любого города России.</p>
        <p><a class="btn btn-default" href="https://www.aviasales.ru/routes/mow/tr">Посмотреть города вылета &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Где отдохнуть</h2>
        <p>Мы работаем с отелями по всему миру и готовы предложить вам самый лучший.</p>
        <p><a class="btn btn-default" href="{% url 'links' %}">Выбрать место для отдыха &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Сайт туристической компании</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img width="90" height="90" src="{% static 'app/content/барселона1.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">Поиск тура</a></li>
                    <li><a href="{% url 'links' %}">Идеи для отдыха</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'feedback' %}">Отзывы о нашей работе</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить статью</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видеообзоры</a></li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Туристическая компания БарселонаТревел</p>
        </footer>
    </div>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}
<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>
<div class="jumbotron">
    <h1>Лучшие курорты Испании</h1>
    <p class="lead">Мы собрали на этой странице наши лучшие туры в Испанию в 2023 году. Спешите выбрать оптимальное предложение поездки в Испанию по самым низким ценам.</p>
    <p><a href="https://blog.ostrovok.ru/kurorty-ispanii/" target="_blank"> <img width="1000" height="610" src="{% static 'app/content/испания.jpg' %}" alt="Logo 1" /></a></p>
</div>
<div class="jumbotron">
    <h1>Лучшие курорты Бали</h1>
    <p class="lead">Отдых на Бали. Словно магнит, притягивает к себе Бали путешественников со всего мира — романтиков и влюбленных, семейных пар и одиноких туристов.</p>
    <a href="https://vc.ru/migrate/623438-10-luchshih-mest-dlya-poseshcheniya-na-bali" target="_blank"> <img width="1000" height="610" src="{% static 'app/content/бали.jpeg' %}" alt="Logo 2" /></a>
</div>
<div class="jumbotron">
    <h1>Лучшие курорты Таиланда</h1>
    <p class="lead">Когда в Москве снег, на тайских пляжах палящее солнце. А ещё Тай — страна для перезагрузки, где можно и загореть, и познать дзен. Что там такого в этом Таиланде. Два моря: Андаманское и Южно-Китайское (точнее, его Сиамский залив). Остров Пхукет в Андаманском, остров Самуи — в Сиамском заливе, на берегах залива — Бангкок и Паттайя. </p>
        <a href="https://howtrip.ru/10-luchshikh-mest-dlya-otdykha-v-taylande/" target="_blank"> <img width="1000" height="610" src="{% static 'app/content/таиланд.jpg' %}" alt="Logo 3" /></a>
</div>
<div class="jumbotron">
    <h1>Лучшие курорты Шри-Ланки</h1>
    <p class="lead">Шри-Ланка — остров, куда едут отдыхать круглый год. Пляжный отдых, купание в Индийском океане, поездки по экзотическим местам, полное расслабление, встречи, запоминающиеся навсегда, аутентичная жизнь деревень, вековые традиции — так или иначе именно этого ждут от острова. </p>
        <a href="https://make-trip.ru/sri-lanka/luchshie-kurorty-gde-otdykhat" target="_blank"> <img width="1000" height="610" src="{% static 'app/content/шриланка.jpg' %}" alt="Logo 4" /></a>
</div>
<div class="jumbotron">
    <h1>Лучшие курорты Мальдивских островов</h1>
    <p class="lead">Рассказываем, где лучше отдыхать на Мальдивах. Какие там есть острова и сколько стоит жилье. Как организовать перелет на Мальдивы и как перемещаться между островами. Цены на продукты и еду в ресторанах. Что из сувениров привезти домой.</p>
        <a href="https://travelest.ru/luchshie-kurorty-na-maldivskikh-ostrovakh" target="_blank"> <img width="1000" height="610" src="{% static 'app/content/мальдивы.jpg' %}" alt="Logo 5" /></a>
</div>
        {% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="Зерегистрируйтесь">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Для входа введите логин и пароль</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Введен некорретный логин или пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Здравствуйте, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}

   <h3>Добавить статью</h3>
   <form method="POST" enctype="multipart/form-data"> 
       {% csrf_token %}
       <div>
           {{blogform.as_p}}
           <button type = "submit" class="save btn btn-default"> Сохранить статью </button>
       </div>
   </form>
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<br><br><h2>Регистрация пользователя</h2>

<form method="POST">
    {% csrf_token %}

    <div>

        {{ regform.as_p}}

        <button type="submit" class="save btn btn-default"> Зарегистрировать </button>

    </div>

</form>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}
{% block content %}

<br>
<h1>{{ title }}</h1>
<br />
<div>
    <h2> Видеоролик 1 </h2>
    <video src="media/video1.mp4" controls="controls" width="400" height="300" poster="media/еда.JPG"></video>
</div>
<hr />
<div>
    <h2> Видеоролик 2 </h2>
    <video src="media/video2.mp4" controls="controls" width="400" height="300" poster="media/бухты.JPG"></video>
</div>
{% endblock %}